#pragma once
#include<stdio.h>
#define SYM_NAME L"\\\\.\\Zlz Ndis6.30 Filter SymbolLink"

#define PACKET_TYPE_ADAPTERINFO 1
#define PACKET_TYPE_NETPACKET 2
#define IOCTL_SHOWADAPTER (ULONG)CTL_CODE(FILE_DEVICE_UNKNOWN,0x911,METHOD_BUFFERED,FILE_WRITE_DATA|FILE_READ_DATA)
#define IOCTL_GETRAWDATA (ULONG)CTL_CODE(FILE_DEVICE_UNKNOWN,0x912,METHOD_BUFFERED,FILE_WRITE_DATA|FILE_READ_DATA) 