import "oaidl.idl";
import "ocidl.idl";

typedef struct _ParamA
{
    int a;
}ParamA;

typedef [switch_type(int)] union _UNIONPARAM
{
    [case(1)] ParamA	Param;
    [case(2)]  int b;
    [case(3)] int c;
    [case(4)] int d;
}UNIONPARAM;

typedef struct _Param
{
    int Type;
    [switch_is(Type)] UNIONPARAM uParam;
}Param,*PParam;

[
    uuid("8457600F-988B-4C84-866B-69CD93B5CF77"),
    version(1.0)
]

interface RpcService
{
    HRESULT RpcCall([in, out]PParam lpParam);
    void    RpcAsyncCall([in, out]PParam lpParam);
}

[
    uuid("BC47C629-BC9C-4668-AAD4-19928D9392FD"),
    version(1.0),
    helpstring("rpc Library")
]

library RpcLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");
};